name: Build and deploy API - app-techstore-api-natanael

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build API
        run: dotnet build TechStore.Products.Api/TechStore.Products.Api.csproj --configuration Release

      - name: Publish API
        run: dotnet publish TechStore.Products.Api/TechStore.Products.Api.csproj --configuration Release --no-build --output "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F62CAE60E7384D418A8C92ADBA00EA7E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_866C71C0BEA7499B992B5A7F89FD2C2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_76FD42FE301C4A1EB8CBA6C881D058BE }}

      - name: Deploy API to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-techstore-api-natanael
          slot-name: Production
          package: .
